server:
   port: 8443         
spring:
   profiles.active: ssl, oauth2
   security:
      user:
         name: "client"
         password: "password"   
         roles: "USER"
     
logging.level.org.springframework.security.oauth2: DEBUG                  