server:
   port: 9443   
   ssl:
      key-store-type: "PKCS12"
      key-store: "classpath:ssl/demo.p12"
      key-store-password: "password"
      key-alias: "demo"     
security.require-ssl: true   