server:
   port: 9000
spring:
   security:
      user:
         name: "enduser"
         password: "password"   
         roles: "USER"
security:
   oauth2:
      client:        
         client-id: "client"
         client-secret: "password"
         authorized-grant-types: refresh_token, password
         scope: openid         
         access-token-validity-seconds: 6000
         refresh-token-validity-seconds: 6000                 
      authorization:         
         jwt:
            key-value: "12345"            